### ISSUE TITLE
List 4.7 Example of the logical operation with T does not work

### ISSUE THREAD

**Issue by brawaga** [Konamiman/MSX2-Technical-Handbook#10]

**Comment by brawaga** [comment]
Cannot create branch to proceed with pull request, so correction is the following:
1070 LINE (50,50)-(60,100),48,B : PAINT (51,51),156,48

**Comment by Konamiman** [comment]
Hi @brawaga, thanks for your contribution and apologies for taking so long, but the typo is now fixed by https://github.com/Konamiman/MSX2-Technical-Handbook/pull/18. Could you please tell me which are the other listings that don't work, either in a comment here or in a new issue? Thank you!
